// Static list of HS / EU Combined Nomenclature chapters in Polish.
// Source: WCO Harmonized System + EU CN Annex I, valid for 2024+.
// Used as the candidate set for the first descent step (chapter pick)
// so we don't have to derive chapter labels from a tree walk.

export interface HsChapter {
  code: string
  description: string
}

export const HS_CHAPTERS_PL: HsChapter[] = [
  { code: '01', description: 'Zwierzęta żywe' },
  { code: '02', description: 'Mięso i podroby jadalne' },
  { code: '03', description: 'Ryby i skorupiaki, mięczaki i pozostałe bezkręgowce wodne' },
  { code: '04', description: 'Produkty mleczarskie; jaja ptasie; miód naturalny; jadalne produkty pochodzenia zwierzęcego, gdzie indziej niewymienione ani niewłączone' },
  { code: '05', description: 'Produkty pochodzenia zwierzęcego, gdzie indziej niewymienione ani niewłączone' },
  { code: '06', description: 'Drzewa żywe i pozostałe rośliny; bulwy, korzenie i podobne; cięte kwiaty i ozdobne liście' },
  { code: '07', description: 'Warzywa oraz niektóre korzenie i bulwy, jadalne' },
  { code: '08', description: 'Owoce i orzechy jadalne; skórki owoców cytrusowych lub melonów' },
  { code: '09', description: 'Kawa, herbata, maté (herbata paragwajska) i przyprawy' },
  { code: '10', description: 'Zboża' },
  { code: '11', description: 'Produkty przemysłu młynarskiego; słód; skrobie; inulina; gluten pszenny' },
  { code: '12', description: 'Nasiona i owoce oleiste; ziarna, nasiona i owoce różne; rośliny przemysłowe lub lecznicze; słoma i pasza' },
  { code: '13', description: 'Szelak; gumy, żywice oraz pozostałe soki i ekstrakty roślinne' },
  { code: '14', description: 'Materiały roślinne do wyplatania; produkty pochodzenia roślinnego, gdzie indziej niewymienione ani niewłączone' },
  { code: '15', description: 'Tłuszcze i oleje pochodzenia zwierzęcego, roślinnego lub mikrobiologicznego oraz produkty ich rozkładu; gotowe tłuszcze jadalne; woski pochodzenia zwierzęcego lub roślinnego' },
  { code: '16', description: 'Przetwory z mięsa, ryb, skorupiaków, mięczaków lub pozostałych bezkręgowców wodnych, lub z owadów' },
  { code: '17', description: 'Cukry i wyroby cukiernicze' },
  { code: '18', description: 'Kakao i przetwory z kakao' },
  { code: '19', description: 'Przetwory ze zbóż, mąki, skrobi lub mleka; pieczywa cukiernicze' },
  { code: '20', description: 'Przetwory z warzyw, owoców, orzechów lub pozostałych części roślin' },
  { code: '21', description: 'Różne przetwory spożywcze' },
  { code: '22', description: 'Napoje bezalkoholowe, alkoholowe i ocet' },
  { code: '23', description: 'Pozostałości i odpady przemysłu spożywczego; gotowa pasza dla zwierząt' },
  { code: '24', description: 'Tytoń i przemysłowe namiastki tytoniu; produkty, nawet zawierające nikotynę, przeznaczone do wdychania bez spalania; pozostałe wyroby zawierające nikotynę przeznaczone do wprowadzania nikotyny do ciała ludzkiego' },
  { code: '25', description: 'Sól; siarka; ziemie i kamienie; materiały gipsowe, wapno i cement' },
  { code: '26', description: 'Rudy metali, żużel i popiół' },
  { code: '27', description: 'Paliwa mineralne, oleje mineralne i produkty ich destylacji; substancje bitumiczne; woski mineralne' },
  { code: '28', description: 'Chemikalia nieorganiczne; organiczne lub nieorganiczne związki metali szlachetnych, metali ziem rzadkich, pierwiastków promieniotwórczych lub izotopów' },
  { code: '29', description: 'Chemikalia organiczne' },
  { code: '30', description: 'Produkty farmaceutyczne' },
  { code: '31', description: 'Nawozy' },
  { code: '32', description: 'Ekstrakty garbników lub środków barwiących; garbniki i ich pochodne; barwniki, pigmenty i pozostałe substancje barwiące; farby i lakiery; kit i pozostałe masy uszczelniające; atramenty' },
  { code: '33', description: 'Olejki eteryczne i rezinoidy; preparaty perfumeryjne, kosmetyczne lub toaletowe' },
  { code: '34', description: 'Mydło, organiczne środki powierzchniowo czynne, preparaty piorące, preparaty smarowe, woski syntetyczne, woski preparowane, preparaty do czyszczenia lub szorowania, świece i artykuły podobne, pasty modelarskie, „woski dentystyczne" oraz preparaty dentystyczne produkowane na bazie gipsu' },
  { code: '35', description: 'Substancje białkowe; skrobie modyfikowane; kleje; enzymy' },
  { code: '36', description: 'Materiały wybuchowe; produkty pirotechniczne; zapałki; stopy piroforyczne; niektóre materiały łatwo palne' },
  { code: '37', description: 'Materiały fotograficzne lub kinematograficzne' },
  { code: '38', description: 'Produkty chemiczne różne' },
  { code: '39', description: 'Tworzywa sztuczne i artykuły z nich' },
  { code: '40', description: 'Kauczuk i artykuły z kauczuku' },
  { code: '41', description: 'Skóry i skórki surowe (inne niż skóry futerkowe) oraz skóry wyprawione' },
  { code: '42', description: 'Artykuły ze skóry wyprawionej; wyroby siodlarskie i rymarskie; artykuły podróżne, torebki i podobne pojemniki; artykuły z jelit zwierzęcych (innych niż z jelit jedwabników)' },
  { code: '43', description: 'Skóry futerkowe i futra sztuczne; wyroby z nich' },
  { code: '44', description: 'Drewno i artykuły z drewna; węgiel drzewny' },
  { code: '45', description: 'Korek i artykuły z korka' },
  { code: '46', description: 'Wyroby ze słomy, z esparto lub pozostałych materiałów do wyplatania; wyroby koszykarskie oraz wyroby z wikliny' },
  { code: '47', description: 'Masa włóknista z drewna lub z pozostałego włóknistego materiału celulozowego; papier lub tektura, z odzysku (makulatura i odpady)' },
  { code: '48', description: 'Papier i tektura; artykuły z masy papierniczej, papieru lub tektury' },
  { code: '49', description: 'Książki, gazety, obrazki i pozostałe wyroby przemysłu poligraficznego, drukowane; manuskrypty, maszynopisy i plany' },
  { code: '50', description: 'Jedwab' },
  { code: '51', description: 'Wełna, cienka lub gruba sierść zwierzęca; przędza i tkanina z włosia końskiego' },
  { code: '52', description: 'Bawełna' },
  { code: '53', description: 'Pozostałe włókna roślinne; przędza papierowa i tkaniny z przędzy papierowej' },
  { code: '54', description: 'Włókna ciągłe chemiczne; pasek i tym podobne z materiałów włókienniczych chemicznych' },
  { code: '55', description: 'Włókna odcinkowe chemiczne' },
  { code: '56', description: 'Wata, filc i włókniny; przędze specjalne; szpagat, powrozy, linki i liny oraz wyroby z nich' },
  { code: '57', description: 'Dywany i pozostałe pokrycia podłogowe włókiennicze' },
  { code: '58', description: 'Tkaniny specjalne; tkaniny włókiennicze pętelkowe; koronki; tkaniny obiciowe; pasmanteria; hafty' },
  { code: '59', description: 'Tkaniny impregnowane, powleczone, pokryte lub laminowane; artykuły włókiennicze do zastosowań technicznych' },
  { code: '60', description: 'Dzianiny' },
  { code: '61', description: 'Artykuły odzieżowe i dodatki odzieżowe, dziane' },
  { code: '62', description: 'Artykuły odzieżowe i dodatki odzieżowe, niedziane' },
  { code: '63', description: 'Pozostałe konfekcjonowane artykuły włókiennicze; zestawy; odzież używana i używane artykuły włókiennicze; szmaty' },
  { code: '64', description: 'Obuwie, getry i podobne; części tych artykułów' },
  { code: '65', description: 'Nakrycia głowy i ich części' },
  { code: '66', description: 'Parasole, parasole przeciwsłoneczne, laski, stołki myśliwskie, bicze, szpicruty i ich części' },
  { code: '67', description: 'Preparowane pióra i puch oraz wyroby z piór lub puchu; sztuczne kwiaty; wyroby z włosów ludzkich' },
  { code: '68', description: 'Artykuły z kamienia, gipsu, cementu, azbestu, miki lub podobnych materiałów' },
  { code: '69', description: 'Wyroby ceramiczne' },
  { code: '70', description: 'Szkło i wyroby ze szkła' },
  { code: '71', description: 'Perły naturalne lub hodowlane, kamienie szlachetne lub półszlachetne, metale szlachetne, metale platerowane metalem szlachetnym i artykuły z nich; sztuczna biżuteria; monety' },
  { code: '72', description: 'Żeliwo i stal' },
  { code: '73', description: 'Artykuły z żeliwa lub stali' },
  { code: '74', description: 'Miedź i artykuły z miedzi' },
  { code: '75', description: 'Nikiel i artykuły z niklu' },
  { code: '76', description: 'Aluminium i artykuły z aluminium' },
  { code: '78', description: 'Ołów i artykuły z ołowiu' },
  { code: '79', description: 'Cynk i artykuły z cynku' },
  { code: '80', description: 'Cyna i artykuły z cyny' },
  { code: '81', description: 'Pozostałe metale nieszlachetne; cermetale; artykuły z nich' },
  { code: '82', description: 'Narzędzia, przybory, noże, łyżki i widelce z metali nieszlachetnych; ich części z metali nieszlachetnych' },
  { code: '83', description: 'Artykuły różne z metali nieszlachetnych' },
  { code: '84', description: 'Reaktory jądrowe, kotły, maszyny i urządzenia mechaniczne; ich części' },
  { code: '85', description: 'Maszyny i urządzenia elektryczne oraz ich części; rejestratory i odtwarzacze dźwięku, rejestratory i odtwarzacze obrazu i dźwięku oraz części i akcesoria do tych artykułów' },
  { code: '86', description: 'Lokomotywy pojazdów szynowych, tabor szynowy i jego części; osprzęt i elementy torów kolejowych lub tramwajowych, oraz ich części; mechaniczne (włączając elektromechaniczne) wszelkich rodzajów urządzenia sygnalizacyjne dla ruchu' },
  { code: '87', description: 'Pojazdy nieszynowe oraz ich części i akcesoria' },
  { code: '88', description: 'Statki powietrzne, statki kosmiczne i ich części' },
  { code: '89', description: 'Statki, łodzie oraz konstrukcje pływające' },
  { code: '90', description: 'Przyrządy i aparatura, optyczne, fotograficzne, kinematograficzne, pomiarowe, kontrolne, precyzyjne, medyczne lub chirurgiczne; ich części i akcesoria' },
  { code: '91', description: 'Zegary i zegarki oraz ich części' },
  { code: '92', description: 'Instrumenty muzyczne; części i akcesoria do takich artykułów' },
  { code: '93', description: 'Broń i amunicja; ich części i akcesoria' },
  { code: '94', description: 'Meble; pościel, materace, stelaże pod materace, poduszki i podobne wypychane artykuły wyposażeniowe; lampy i oprawy oświetleniowe, gdzie indziej niewymienione ani niewłączone; podświetlane znaki, podświetlane tablice i tym podobne; budynki prefabrykowane' },
  { code: '95', description: 'Zabawki, gry i artykuły sportowe; ich części i akcesoria' },
  { code: '96', description: 'Artykuły przemysłowe różne' },
  { code: '97', description: 'Dzieła sztuki, przedmioty kolekcjonerskie i antyki' },
  { code: '98', description: 'Kompletny zakład przemysłowy (rezerwowe / uzupełniające zastosowanie krajowe)' },
  { code: '99', description: 'Specjalne kody nomenklatury (rezerwowe / uzupełniające zastosowanie krajowe)' },
]

export function findChapterDescription(chapterCode: string): string | null {
  return HS_CHAPTERS_PL.find((c) => c.code === chapterCode)?.description ?? null
}
